
//USER ACTIONS
export const ADDUSER="ADDUSER"
export const DELUSER="DELUSER"
export const UPDATEUSER="UPDATEUSER"

//RIDES ACTIONS
export const ADDRIDE="ADDRIDE"
export const DELRIDE="DELRIDE"
export const UPDATERIDE="UPDATERIDE"
export const GETALLRIDES="GETALLRIDES"
